apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_DEFAULT_REGION}
  version: "1.27"
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}

vpc:
  id: vpc-01b5542b0e0ac60cf
  cidr: 10.0.0.0/16
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-08624f6c4b1a0cfd7
      ap-northeast-2b:
        id: subnet-0cf3f9a9bfdf01e65
      ap-northeast-2c:
        id: subnet-030401ec4652d04bc

managedNodeGroups:
- instanceType: c5.large
  amiFamily: AmazonLinux2
  name: ${CLUSTER_NAME}-ng
  privateNetworking: true
  desiredCapacity: 2
  minSize: 2
  maxSize: 20
  privateNetworking: true
  iam:
    withAddonPolicies:
      imageBuilder: true
      albIngress: true
      cloudWatch: true
      autoScaler: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: ${CLUSTER_NAME}-karpenter
    attachPolicyARNs:
    - arn:aws:iam::${AWS_ACCOUNT_ID}:policy/KarpenterControllerPolicy-${CLUSTER_NAME}
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

addons:
- name: vpc-cni
  version: latest
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
